# Generated by Django 5.0.7 on 2024-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lote',
            fields=[
                ('codigo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('manzana', models.IntegerField(default=0)),
                ('lote', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('vendedor', models.CharField(max_length=20)),
            ],
        ),
    ]
