# Generated by Django 5.0.7 on 2024-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='manzana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
