# Generated by Django 5.0.7 on 2024-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_lote_fecha_alter_lote_lote_alter_lote_manzana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
