# Generated by Django 5.0.7 on 2024-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_alter_lote_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
